import { useState } from 'react';
import type { AgentEvent } from '@/agent/types';
import { failureList, files, sourceLabel, type ChangeReceipt, type ChangeTransaction, type Operation } from '@/transactions/change-set';
const descriptions: Record<Operation['action'], string> = { darken_cta: 'CTA #60A5FA / #0F172A → #2563EB / #FFFFFF', change_text_color: 'CTA text → #0F172A · retain #60A5FA', expanded_navigation: 'Navigation compact → expanded (540px)', mobile_safe_navigation: 'Navigation expanded → mobile-safe', compact_field: 'Email label associated → visual-only', associate_label: 'Email label visual-only → associated' };
export function ProposedOperations({ tx }: { tx: ChangeTransaction | null }) {
  const candidate = tx?.changeSet.candidates.at(-1);
  return <section className="panel p-5"><div className="section-kicker">PROPOSED PATCH OPERATIONS</div><h2 className="mt-2 text-base font-semibold">{candidate ? `${candidate.id === 'candidate-a' ? 'Candidate A' : 'Candidate B'} · ${sourceLabel(candidate.source)}` : 'One request. Three files. Atomic acceptance.'}</h2><p className="mt-2 text-xs text-slate-400">{candidate?.summary ?? 'The planner returns bounded operations. No arbitrary source code is executed.'}</p><div className="mt-4 space-y-3">{files.map(f => { const op = candidate?.operations.find(op => op.fixture === f.id); return <div key={f.id} className="border-t border-white/10 pt-3"><div className="font-mono text-xs text-slate-200">{f.name}</div><p className="mt-1 text-xs text-sky-200">{op ? descriptions[op.action] : 'Awaiting structured proposal'}</p></div>; })}</div></section>;
}
export function TransactionTrace({ events, tx }: { events: AgentEvent[]; tx: ChangeTransaction | null }) {
  return <section className="panel p-5"><div className="section-kicker">ATOMIC TRANSACTION TRACE</div><div className="mt-3 flex gap-2 flex-wrap">{tx?.changeSet.candidates.map(c => <span className={`status-pill ${c.status === 'rejected' ? 'status-fail' : c.status === 'accepted' ? 'status-pass' : 'status-warn'}`} key={c.id}>{c.id.replace('candidate-', '')} · {c.status.replaceAll('_', ' ')}</span>)}</div><ol className="trace-list mt-3 space-y-4" aria-label="Transaction events">{events.length === 0 && <li className="text-sm text-slate-400">Apply → render → verify → reject → rollback → replan → receipt.</li>}{events.map(e => <li key={e.id} className="border-l border-white/15 pl-3"><div className={`text-xs font-semibold ${e.tone === 'danger' ? 'text-rose-300' : e.tone === 'success' ? 'text-emerald-300' : e.tone === 'warning' ? 'text-amber-200' : 'text-slate-200'}`}>{e.title}</div><p className="mt-1 text-xs leading-5 text-slate-400">{e.detail}</p></li>)}</ol></section>;
}
export function ChangeSetReceipt({ receipt }: { receipt: ChangeReceipt }) {
  const [exported, setExported] = useState(false);
  const exportJSON = () => { const url = URL.createObjectURL(new Blob([JSON.stringify(receipt, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `${receipt.receiptId}.json`; document.body.append(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); setExported(true); };
  const e = receipt.evaluation;
  const candidateA = receipt.candidateHistory.find(candidate => candidate.id === 'candidate-a')!;
  const candidateB = receipt.candidateHistory.find(candidate => candidate.id === 'candidate-b')!;
  const rollback = receipt.rollback!;
  return <section className="panel p-5" data-testid="receipt"><div className="flex flex-wrap justify-between gap-3"><div><div className="section-kicker">CONSTRAINT RECEIPT V2 · {receipt.receiptId}</div><h2 className={`mt-2 text-xl font-semibold ${receipt.outcome === 'accepted' ? 'text-emerald-300' : 'text-amber-300'}`}>{receipt.outcome === 'accepted' ? 'Change set accepted and verified' : 'Approved exception · brand remains FAIL'}</h2></div><button onClick={exportJSON} className="plain-button">{exported ? 'JSON exported' : 'Export JSON'}</button></div><p className="mt-3 text-xs text-slate-400">{receipt.changeRequest}</p>
    <div className="mt-4 grid gap-3 lg:grid-cols-4" aria-label="Receipt decision summary">
      <div className="receipt-step"><span>Candidate A</span><strong className="text-rose-300">{candidateA.verification?.passed}/{candidateA.verification?.total} · REJECTED</strong><p>{failureList(candidateA.verification!).map(item => item.replace('pricing-card', 'Pricing').replace('mobile-header', 'Header').replace('checkout-form', 'Form')).join(' · ')}</p></div>
      <div className="receipt-step"><span>Atomic rollback</span><strong className="text-emerald-300">{e.restoredFixtures} RESTORED · {rollback.result.passed}/{rollback.result.total}</strong><p>Saved baseline re-measured after restoration.</p></div>
      <div className="receipt-step"><span>Human policy</span><strong className="text-sky-200">{receipt.humanDecision?.replaceAll('_', ' ').toUpperCase()}</strong><p>{receipt.humanDecision === 'preserve_brand' ? 'Protected token retained.' : 'Pricing brand failure explicitly waived.'}</p></div>
      <div className="receipt-step"><span>Candidate B</span><strong className={receipt.outcome === 'accepted' ? 'text-emerald-300' : 'text-amber-300'}>{candidateB.verification?.passed}/{candidateB.verification?.total} · {receipt.outcome === 'accepted' ? 'ACCEPTED' : 'APPROVED EXCEPTION'}</strong><p>{receipt.outcome === 'accepted' ? 'All measured gates passed.' : 'Brand remains measured FAIL; policy allows only that exception.'}</p></div>
    </div>
    <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{[['Attempts', e.attempts], ['Files touched', e.filesTouched], ['Candidate checks', e.candidateChecks], ['Rejected', e.rejectedCandidates], ['Rollbacks', e.rollbacks], ['Human decisions', e.humanDecisions], ['Model calls', e.modelCalls], ['Final checks', e.finalChecks]].map(([label, value]) => <div key={label} className="metric-card"><span>{label}</span><strong>{value}</strong></div>)}</div><p className="mt-4 text-xs text-slate-300">Runtime source: {sourceLabel(receipt.source)} · {e.totalMeasuredChecks} total measured checks including baseline and rollback</p><details className="mt-4 text-xs text-slate-400"><summary className="cursor-pointer text-sky-200">Full JSON evidence and limitations</summary><p className="mt-3 break-all">Transaction: {receipt.transactionId}</p><p>{receipt.filesTouched.join(' · ')}</p><p className="mt-2">{receipt.scope}</p><pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap break-all text-[10px]">{JSON.stringify(receipt, null, 2)}</pre></details></section>;
}
