import { files, type VerificationMatrix as Matrix } from '@/transactions/change-set';
export function VerificationMatrix({ result, label, exception = false }: { result: Matrix | null; label: string; exception?: boolean }) {
  const rows = [{ label: 'Accessibility', key: 'accessibilityPass' }, { label: 'Brand token', key: 'brandPass' }, { label: '375px layout', key: 'layoutPass' }] as const;
  return <section className="panel p-5" aria-label="Verification matrix">
    <div className="flex flex-wrap justify-between items-start gap-3"><div><div className="section-kicker">DETERMINISTIC VERIFICATION MATRIX</div><h2 className="mt-2 text-lg font-semibold">One failing cell blocks the change set.</h2><p className="mt-1 text-xs text-slate-400">{label}</p></div><span data-testid="matrix-outcome" className={`status-pill ${result ? result.overallPass ? 'status-pass' : exception ? 'status-warn' : 'status-fail' : ''}`}>{result ? `${result.passed}/${result.total} · ${result.overallPass ? 'VERIFIED' : exception ? 'EXCEPTION' : 'REJECTED'}` : 'NOT RUN'}</span></div>
    <div className="mt-5 overflow-x-auto"><table className="verification-table"><caption className="sr-only">Measured browser checks for each fixture</caption><thead><tr><th scope="col">Contract</th>{files.map(f => <th scope="col" key={f.id}>{f.short}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.key}><th scope="row">{row.label}</th>{files.map(f => { const measured = result?.fixtures.find(r => r.fixture === f.id); const pass = measured?.[row.key]; return <td key={f.id} data-testid={`${f.id}-${row.key}`}><span className={measured ? pass ? 'text-emerald-300' : 'text-rose-300' : 'text-slate-500'}>{measured ? pass ? '✓ PASS' : '✕ FAIL' : '—'}</span>{exception && f.id === 'pricing-card' && row.key === 'brandPass' && !pass && <small className="block text-amber-300">approved waiver</small>}</td>; })}</tr>)}</tbody></table></div>
    {result && <details className="mt-4 text-xs text-slate-400"><summary className="cursor-pointer text-sky-200">Inspect browser evidence</summary><div className="mt-3 grid gap-3 sm:grid-cols-3">{result.fixtures.map(r => <div key={r.fixture}><strong>{files.find(f => f.id === r.fixture)?.name}</strong><p className="mt-1">Contrast: {r.contrastRatio.toFixed(2)}:1</p><p>{r.width}px viewport / {r.scrollWidth}px content</p><p className="break-all">Brand: {r.brandColor}</p><p>axe: {r.axeViolations.map(v => `${v.id} (${v.nodes})`).join(', ') || '0 selected-rule violations'}</p></div>)}</div></details>}
    <p className="mt-4 text-[11px] text-slate-500">axe button-name + label · CTA contrast math · computed brand surfaces · DOM geometry. Selected automated checks, not full WCAG certification.</p>
  </section>;
}
